services:

    bitcoin:
        container_name: "bitcoin"
        build:
          context: ./
          dockerfile: ./btc/Dockerfile
        ports:
            - "38332:38332"
            - "38333:38333"
        expose:
            - "38332"
            - "38333"
        volumes:
            - ./btc/data:/root/.bitcoin/
        command: ["./btc_entrypoint.sh"]
        networks:
            - network_conn
    postgres_container:
        container_name: "postgres_container"
        image: postgres:12
        restart: unless-stopped
        ports:
            - "5442:5432"
        volumes:
            - ./psql/schema/operator.sql:/docker-entrypoint-initdb.d/operator.sql
            - ./psql/data:/var/lib/postgresql/data
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: user1
            POSTGRES_PASSWORD: password1
            POSTGRES_DB: databasename
        networks:
            - network_conn

    motif:
        container_name: "motif"
        build:
          context: ./
          dockerfile: ./motif/Dockerfile
        ports:
            - "8080:8080"
        expose:
            - "8080"
        volumes: 
        - ./motif/data:/app/wallet/
        - ./configs:/app/motif-node/configs/
        command : ["./wait_for_it.sh", "postgres_container:5432", "--", "./motif_entrypoint.sh"]
        networks:
            - network_conn
        environment:
            - DATABASE_URL=databasename://user:password@postgres_container/databasename
        depends_on:
            - postgres_container
        links:
            - postgres_container
        
networks:
  network_conn:
    # external: true